// apps/nextjs/src/app/_components/page-switcher.tsx
"use client";

import { Check, ChevronsUpDown } from "lucide-react";
import { Button } from "~/shared/ui/button";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
} from "~/shared/ui/dropdown-menu";

const frameworks = [{ id: "nextjs", label: "Next.js" }] as const;

function getFrameworkFromHostname(hostname: string) {
  const subdomain = hostname.split(".")[0];
  return frameworks.find((f) => f.id === subdomain);
}

export function PageSwitcher() {
  const hostname =
    typeof window !== "undefined" ? window.location.hostname : "";
  const current = getFrameworkFromHostname(hostname) ?? frameworks[0];

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          className="min-w-31 justify-between"
        >
          {current.label}
          <ChevronsUpDown className="h-3.5 w-3.5 opacity-50" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="start" className="min-w-[160px]">
        <DropdownMenuLabel>Frameworks</DropdownMenuLabel>
        {frameworks.map((fw) => (
          <DropdownMenuItem key={fw.id} asChild>
            <a
              href={`https://${fw.id}.moda.ravecat.io`}
              className="flex items-center justify-between"
            >
              {fw.label}
              {fw.id === current.id && <Check className="h-4 w-4 opacity-50" />}
            </a>
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// apps/sveltekit/src/shared/layout/page-switcher.svelte
<script lang="ts">
  import { browser } from "$app/environment";
  import CheckIcon from "@lucide/svelte/icons/check";
  import ChevronsUpDownIcon from "@lucide/svelte/icons/chevrons-up-down";
  import { Button } from "$shared/ui/button/index.js";
  import * as DropdownMenu from "$shared/ui/dropdown-menu/index.js";
  import {
    defaultFramework,
    frameworks,
    getFrameworkByHostname,
  } from "$shared/navigation.js";

  const currentFramework = browser
    ? (getFrameworkByHostname(window.location.hostname) ?? defaultFramework)
    : defaultFramework;

  function visitFramework(href: string) {
    if (!browser) {
      return;
    }

    window.location.assign(href);
  }
</script>

<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    {#snippet child({ props })}
      <Button
        {...props}
        variant="outline"
        size="sm"
        class="min-w-[7.75rem] justify-between"
      >
        {currentFramework.label}
        <ChevronsUpDownIcon class="size-3.5 opacity-50" />
      </Button>
    {/snippet}
  </DropdownMenu.Trigger>
  <DropdownMenu.Content align="start" class="min-w-40">
    <DropdownMenu.Label>Frameworks</DropdownMenu.Label>
    {#each frameworks as framework (framework.id)}
      <DropdownMenu.Item
        class="flex items-center justify-between"
        onclick={() => visitFramework(framework.href)}
      >
        <span>{framework.label}</span>
        {#if framework.id === currentFramework.id}
          <CheckIcon class="size-4 opacity-50" />
        {/if}
      </DropdownMenu.Item>
    {/each}
  </DropdownMenu.Content>
</DropdownMenu.Root>
